# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'Azul Digital' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Azul Digital
# pod 'Firebase'	
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'

end
